### ISSUE TITLE
ruby2js filter

### ISSUE THREAD

**Issue by rubydesign** [HarlemSquirrel/language-haml#76]
I've been using atom + haml in all my rails projects for years, so am basically addicted :-)

Now i am coding more js, mostly snippets in haml, and have got Sam Ruby's excellent [ruby2js](https://github.com/rubys/ruby2js) to work with haml. It basically lets you write ruby syntax but it transforms it one to one to js. So ruby syntax, js semantics.

Basically i would like a ruby2js highlighting. This should not be too difficult as a :ruby filter is already supported. If you want i can try, but i suspect it's almost a one-liner.

Thanks for taking this over (if i understood right)

**Comment by HarlemSquirrel** [comment]
Hello @dancinglightning ruby2js sounds pretty cool! Could you provide a Haml sample with ruby2js for us to test out? A screenshot of it not working would be helpful too!

**Comment by dancinglightning** [comment]
Hi @HarlemSquirrel 
I have been writing js and only testing the ruby2js (doing vue, which is fun). In short nothing is committed - no show :-(

But it really is just ruby. Sam uses the ruby parser library to do his thing, so it is 100% pure ruby. Basically you can use the existing ruby filter and just make it work for :ruby2js as well.

The reason i have not committed is that it is just impossible to work with code without the highlighting anymore. But i did try the ruby2js out, and it works well. I also tried switching the filter to :ruby and that gave me nice highlighting (but off course it doesn't work anymore). 

Here is what i want to transform https://github.com/rubyclerks/office_clerk/blob/master/app/views/manage/reports.html.haml
Sam has made it so that defining a class makes a prototype that can be assigned to the Vue.methods or computed: attributes. That would break the code up nicely.

**Comment by HarlemSquirrel** [comment]
@dancinglightning I cannot see that file you linked. Are you able to create a gist or share another file? I'll need something to test if it's working when I go to make a change.

**Comment by dancinglightning** [comment]
@HarlemSquirrel Yeah, i just moved the repository. Here is the current link
https://github.com/dancinglightning/ruby_clerks/blob/master/app/views/manage/reports.html.haml

But this is the JS that i *want* to transform. Because of lack of high-lightning i have no live code. But it really is just ruby.

**Comment by HarlemSquirrel** [comment]
I need at least a small sample to test against. Can you convert a small portion of the code you linked above? You could just paste it here in a snippet or as a gist. You said you got it working with haml so you must have something to share? Thanks!

**Comment by dancinglightning** [comment]
Hi,
i made a branch for you. https://github.com/dancinglightning/ruby_clerks/blob/ruby2js/app/views/products/index.html.haml

The required setup can be seen here https://github.com/dancinglightning/ruby_clerks/commit/86cf17b79dd56c9dc0e04e0cdc5d12291751692a#diff-24e48b03fe1af54ed14762acf44a906a

**Comment by HarlemSquirrel** [comment]
Ah OK, now I see. Thank you for that. You want highlighting under a `:ruby2js` to be ruby highlighting. I think I've got it. 

Could you copy the changes in my pull request into your `~/.atom/packages/language-haml/grammars/ruby haml.cson`, reload the window, and let me know if it works?

**Comment by dancinglightning** [comment]
@HarlemSquirrel thanks, but no luck. 
Bit tricky with the space in the name, but figured it, then fixed whitespace (not sure if needed) and to make sure, downloaded the file completely.
But no luck

**Comment by HarlemSquirrel** [comment]
@dancinglightning Sorry, I pushed up a mistake which I've now fixed on that branch. 
Could you try again? Thanks!

**Comment by dancinglightning** [comment]
@HarlemSquirrel sweet, thanks

**Comment by HarlemSquirrel** [comment]
@rubydesign So this branch works for you? If so I can merge this in and deploy a proper release.

**Comment by Throne3d** [comment]
Should this be closed, now #77 is merged?
